### ISSUE TITLE
Filter "Not inline" radio button

### ISSUE THREAD

**Issue by tomtosi** [grommet/grommet-index#14]
Can the draft version of the Filter "Not inline" with checkboxes (http://index.grommet.io/docs/grommet-index/filter) be adapted to create a version of the same control using radio buttons (i.e. single-select)?
![image](https://cloud.githubusercontent.com/assets/17185641/13287169/a3acfbfa-dad3-11e5-8a24-55774163a716.png)

**Comment by ericsoderberghp** [comment]
Fixed in 4e04155bcab21b47769ea43fa7c6ab8a00337fb4.
