### ISSUE TITLE
Tables should convert to tiles when viewing in a smaller display

### ISSUE THREAD

**Issue by HeidiTosi** [grommet/grommet-index#17]
The Activity section of the Ferret app includes a table that appears to be very stable (headers stay with columns when the page is re-sized, etc). When the page is reduced to a smaller display size, the content converts from table format to tiles. We would like to use this behavior in our app.

**Comment by ericsoderberghp** [comment]
This was fixed in fdc63c8ab758c96845abe174340b8fe243fdc460.
