### ISSUE TITLE
Items in Filter overlaps if total height is more than 100vh

### ISSUE THREAD

**Issue by eabay** [grommet/grommet-index#19]
MenuDrop height is fixed to `100vh` and this causes overlapped sections in Filter:

![untitled](https://cloud.githubusercontent.com/assets/158772/13907704/fedac10a-eefc-11e5-9ef0-5e6eb9912a6c.gif)

**Comment by alansouzati** [comment]
thanks the gif definitely helps. Would you mind to create a codepen for your issue. I can try to fork your pen and implement the fix :+1:

**Comment by eabay** [comment]
Sure. I tried to reference the [minified file](https://cdn.rawgit.com/grommet/grommet-index/69ec17573a74f3887829a2d60cf169c2ba042ea9/grommet-index.min.js) under stable branch over rawgit.com but it fails as GrommetIndex is undefined.

Is build version available from grommet.io domain?

**Comment by alansouzati** [comment]
Good point, let me work on creating a codepen that supports grommet-index! :+1:

**Comment by eabay** [comment]
Awesome!

I requested Grommet (cdnjs/cdnjs#7343) and Grommet Index (cdnjs/cdnjs#7344) to be added in cdnjs.

**Comment by alansouzati** [comment]
Nice thanks for working on that!

**Comment by eabay** [comment]
@alansouzati They asked for the files to be included https://github.com/cdnjs/cdnjs/issues/7344#issuecomment-202058422 but CSS file is missing. Grommet Index is not distributed like Grommet.

What should be the approach to create a dist version of Index?

**Comment by alansouzati** [comment]
I will follow up with the folks.

In the meantime take a look at this pen, I was able to use `cdn.rawgit.com` to serve the files directly from git stable branch.

http://codepen.io/alansouzati/pen/xVdeKa

If you want to create a template for grommet-index I can help you tag stuff.

**Comment by eabay** [comment]
rawgit helped for the codepen I referenced in grommet/grommet#468 too but Grommet Index didn't work somehow.

**Comment by alansouzati** [comment]
I think i know what's going on. I will have a look on it today.

**Comment by alansouzati** [comment]
http://index.grommet.io

Now we have a codepen for grommet-index :tada: 

http://codepen.io/grommet/pen/PNKGxN/

And I'm able to reproduce the issue reported here in codepen itself. Just click in the filter icon and we should be able to see the overlapping labels and boxes.

**Comment by eabay** [comment]
Awesome!

Removing the height constraint on MenuDrop will solve the issue but I don't know if this cause another problem somewhere else. What's the purpose of `max-height: 100vh;`?

**Comment by alansouzati** [comment]
@ericsoderberghp for the rescue ?

**Comment by alansouzati** [comment]
I've tested around and removed `max-height` seems to fix the issue and I could find any side effects.

Let's remove it for now and we can double check with Eric when he is back.

I will work on that.

**Comment by alansouzati** [comment]
Now I understand what `max-height: 100vh;` is doing. It is making sure that the drop container does not extrapolate the max height in your view box. I've got a fix for this using `flex-shink: 0` in the child element.

I'm going to push it soon.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/3420781cb8bf1460dce0c2aab667c261b8da17f2

**Comment by eabay** [comment]
Thanks!
