### ISSUE TITLE
Supplying object as query prop in Header component returns [Object object]

### ISSUE THREAD

**Issue by nickjvm** [grommet/grommet-index#24]
PropTypes in `Header` component specify `query` prop should be an object, but the render method only checks if `query` prop is truthy, then runs `query.toString()` resulting in `'[Object object]'`. 

See https://github.com/grommet/grommet-index/blob/master/src/js/components/Header.js#L29.

Codepen: http://codepen.io/nickjvm/pen/dMmWQg

Should the propType be changed to expect a string, or is the query param truly supposed to be an object? If so, a shape should be supplied in prop types and `searchText` definition should be updated to not call `.toString()` on the entire object:

```
const searchText = query && query.text ? query.text.toString() : '';
```

**Comment by epilande** [comment]
`query` prop in Header component should be an instance of `Query` rather than an object. Pending PR to update PropTypes #44. 

Example usage: 

``` javascript
import Query from 'grommet-index/utils/Query';

const query = new Query('hello');

<Index ... query={query} />
```
