### ISSUE TITLE
Dependencies not listed in package.json

### ISSUE THREAD

**Issue by DeanKooiman** [grommet/grommet-index#29]
I had to install the following before I could get gulp dist to run successfully.

+-- inuit-clearfix@0.2.2  extraneous
+-- inuit-defaults@0.2.3
+-- inuit-functions@0.2.0  extraneous
+-- inuit-headings@0.3.1  extraneous
+-- inuit-images@0.3.3  extraneous
+-- inuit-list-bare@0.3.0  extraneous
+-- inuit-lists@0.1.0  extraneous
+-- inuit-mixins@0.2.3
+-- inuit-normalize@3.0.3  extraneous
+-- inuit-page@0.2.1  extraneous
+-- inuit-reset@0.1.1  extraneous
+-- inuit-responsive-settings@0.1.5
+-- inuit-responsive-tools@0.1.3  extraneous
`-- inuit-shared@0.1.5  extraneous

**Comment by alansouzati** [comment]
Thanks for reporting this. Just checking, are you using NPM 2 ? If yes, i believe this is the issue. 

We are relying on NPM 3 with flat dependencies so that we can resolve these dependencies without having to install them manually.

**Comment by bryanjacquot** [comment]
@DeanKooiman can you verify this is an issue after upgrading to NPM 3?

**Comment by bryanjacquot** [comment]
Assuming this is fixed with latest NPM.
