### ISSUE TITLE
When selecting multiple options on a Filter - {count, number} values is shown

### ISSUE THREAD

**Issue by pedrera-x** [grommet/grommet-index#37]
Filters with checkboxes and when selecting more than one option the label showing the selected opts shows - {count, number} values

![image](https://cloud.githubusercontent.com/assets/11410670/16454126/531ae50c-3e07-11e6-835c-4a1f6d1ca8cd.png)

**Comment by jwijay** [comment]
PR pending: https://github.com/grommet/grommet-index/pull/40
