### ISSUE TITLE
Filter Layer with scroll-bars

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet-index#57]
### Expected Behavior

Filter layer should not include any scroll bars (unless it is reaching the size of the view port)
### Actual Behavior

Filter options have scroll bars
### URL, screen shot, or Codepen exhibiting the issue

![image](https://cloud.githubusercontent.com/assets/6320236/18800968/3c0dfb4a-819d-11e6-8bb4-40248417b44a.png)
### Steps to Reproduce
1.  Open application with Grommet Index and updated Gromeet 6.12
2.  Go to filter and open it
3.  Observe
### Your Environment

The problem occurs after updating to Grommet version 6.12, looks like it is influencing Grommet Index layout

- Grommet-index version: 0.4.5
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): WIN desktop

**Comment by ericsoderberghp** [comment]
Fixed in 76408c78426ee6fb04527d7b2418b59013c98d76.
