### ISSUE TITLE
Timestamp component not showing the 'seconds' in date

### ISSUE THREAD

**Issue by vaibhavbhargav** [grommet/grommet-index#59]
Timestamp component not showing the 'seconds' in date.
### Expected Behavior

Timestamp component should give some property to allow the seconds also to be visible in rendered output. The same issue exists in grommet Timestamp component
### Actual Behavior

Timestamp component doesn't show seconds in rendered output, I did not find any propery which drives the display of seconds in the output.
for example, if we pass '4/27/2016 8:23:12' in Timestamp component, it renders 'Apr 27, 2016 8:23 am' excluding 12 from the date
### URL, screen shot, or Codepen exhibiting the issue

http://codepen.io/vaibhavbhargav/pen/dpOaPO?&editors=0010
### Steps to Reproduce
1. pass a date with the format in which it also has seconds.
2. Timestamp component does not show 'seconds' in the output
### Your Environment

- Grommet-index version: latest
- Browser Name and version: chrome
- Operating System and version (desktop or mobile):desktop

**Comment by karatechops** [comment]
I've updated the Timestamp component to support seconds in PR [#890](https://github.com/grommet/grommet/pull/890).
