### ISSUE TITLE
Update to align with grommet 0.6.12

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet-index#60]
I've heard reports of issues with Tile size and Filter layouts from people using stable grommet-index with grommet 0.6.12. We should evaluate what needs to be updated in grommet-index.

**Comment by nickjvm** [comment]
@ericsoderberghp I also noticed an issue with Search not extending the full width in the header.
![hellfire - google chrome - oct 4 2016 2 10 35 pm](https://cloud.githubusercontent.com/assets/4998403/19090582/58ede53e-8a3c-11e6-8121-9a1512e55ffe.png)

**Comment by ericsoderberghp** [comment]
The basics should be addressed now. At some point, we need to revamp grommet-index significantly into discreet components, along the lines of how Grommet refactored Charts.
