### ISSUE TITLE
Index height management?

### ISSUE THREAD

**Issue by hanyoureal** [grommet/grommet-index#69]
How can I adjust the height of an Index component?

My issue is that I am showing grommet-index on a page (say in a Box in a Tab) and Index height exceeds the screen's height, thus there is a scroll bar in the Box. However, the content of the Index exceeds its own height and there is also a scroll bar inside the Index component.

Is there a way to have only one scroll bar in this case?

**Comment by ericsoderberghp** [comment]
I would recommend not using grommet-index. You can compose your own using Header and List. There is an example in grommet-ferret here: https://github.com/grommet/grommet-ferret/blob/master/src/js/components/image/ImageIndex.js

**Comment by ericsoderberghp** [comment]
See prior comment for alternative approach.
