### ISSUE TITLE
Indexes of components are not displaying correctly

### ISSUE THREAD

**Issue by liuwei-HP** [grommet/grommet-index#75]
## Expected Behavior

The second column shows on the right or provide a property for our own definition
## Actual Behavior

Shows on the left and is not aligned
## URL, screen shot, or Codepen exhibiting the issue

![clipboard](https://cloud.githubusercontent.com/assets/20078998/19720024/f616dd7a-9b9e-11e6-9f5d-c6dd5f928967.png)

### Steps to Reproduce
1. Use Index with "list" view type to display data.
2. Open the page Use with Chrome browser.
3. Shows not as expected.
### Your Environment

- Grommet-index version: 1.0.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Win7

**Comment by nickjvm** [comment]
@liuwei-HP I believe this can be achieved with existing props (using `justify="between"`):

``` jsx
<ListItem justify="between">
  <Box>Left-aligned content</Box>
  <Box>Right-aligned content</Box>
</ListItem>
```

[Codepen](https://codepen.io/nickjvm/pen/dpxyeW?&editors=0010)

**Comment by christinHP** [comment]
@nickjvm we use gromment-index/components/Index.js, not grommet/components/ListItem.js

**Comment by nickjvm** [comment]
@christinHP You can combine the usage of both to achieve the layout you need. Use `ListItem` from Grommet and pass your own component to `Index` to use for each item via the `itemComponent` prop.

``` jsx
import Index from 'grommet-index/components/Index';
import ListItem from 'grommet/components/ListItem';

const MyItemComponent = ({item}) => {
  return (
     <ListItem justify="between">
       <Box>{item.name}</Box> {/*left-aligned*/}
       <Box>{item.somethingElse}</Box> {/*right-aligned*/}
     </ListItem>
  );
}

...

export function MyIndex() {
  return (
    <Index view="list" itemComponent={MyItemComponent} ... />
  );
}
```

**Comment by christinHP** [comment]
@nickjvm Thank you, we will try with itemComponent

**Comment by tracybarmore** [comment]
Thanks for the collaboration! We are closing this issue for now. Feel free to reopen if there are more concerns. Thanks!
