### ISSUE TITLE
Enhance search to allow colon in query

### ISSUE THREAD

**Issue by epilande** [grommet/grommet-index#9]
Currently grommet-index/Header will analyze the query & any `:` will be categorized as a filter. 

With real-time search, as soon as you type in another character right after a `:`, it gets stripped out from the Search input & appended to the url. (see attached gif.)

One example is searching for Mac/WWPN addresses like the following:
`1A:B2:3C:D4:5E:F6`
Right after I type in `1A:B`, my search input gets cleared out.

![coloninsearch](https://cloud.githubusercontent.com/assets/3210082/12576283/ab7d836a-c3b6-11e5-847d-93c863d75d3d.gif)

Possible solution: Instead of embedding filter within search text query, create a new property within the query object for specifically filters. However, doing this will require changes on the server, actions, reducers, etc to handle the new object :worried:

**Comment by ericsoderberghp** [comment]
grommet-index 0.3.0 includes changes to handle MAC and WWN addresses in query strings.
